insert into ajiomen(File_name, Product_name, category)values('ajio-1793', 'Mid-Rise Joggers with Side Pockets', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1792', 'Checked Shirt with Patch Pocket', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1791', 'Solid Slim Fit Blazer', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1790', 'Slim Fit Shirt with Patch Pocket', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1789', 'Brand Print Crew-Neck T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1788', 'Mid-Wash Mid-Rise 5-Pocket Slim Jeans', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1787', 'Logo Print Crew-Neck T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1786', 'Crew-Neck Cotton T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1785', 'Cotton Shirt with Patch Pocket', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1784', 'Colourblock Polo T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1783', 'Graphic Print Crew-Neck T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1782', 'Typographic Print Crew-Neck T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1781', 'Micro Print Cotton Shirt with Patch Pocket', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1780', 'Checked Slim Shirt with Roll-Tab Sleeves', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1779', 'Slim Fit Shirt with Patch Pocket', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1778', 'Joggers with Placement Logo Print', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1777', 'Marvel Print Crew-Neck Cotton T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1776', 'Striped Slim Fit Shirt with Band Collar', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1775', 'Graphic Print Crew-Neck T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1774', 'Logo Print Crew-Neck T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1773', 'Placement Typographic Print Crew-Neck Sweatshirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1772', 'Checked Shirt with Patch Pocket', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1771', 'Logo Print Crew-Neck T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1770', 'Slim Fit Polo T-shirt with Contrast Tipping', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1769', 'Quick-Dry Straight Track Pants with Logo Print', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1768', 'Flat-Front Pants with Elasticated Drawstring Waist', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1767', 'Typographic Print Crew-Neck T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1766', 'Checked Slim Fit Shirt with Spread Collar ', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1765', 'Printed Shirt with Shorts', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1764', 'Striped Panelled Crew-Neck T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1763', 'Printed Slim Fit Shirt with Patch Pocket', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1762', 'Tapered Fit Chinos with Button Closure', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1761', 'Heathered Polo T-shirt with Contrast Tipping', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1760', 'AS M NK DF Humor Crew-Neck T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1759', 'Lightly Washed Low-Rise Slim Fit Jeans', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1758', 'Striped Quick-dry Polo T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1757', 'Core leisure track pant ecru s', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1756', 'Nu-Tility City Shorts with Insert Pockets', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1755', 'Printed Slim Fit Shirt with Cutaway Collar', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1754', 'Heathered Quick-Dry Crew-Neck T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1753', 'Solid Jogger Jeans with Drawstring', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1752', 'Brand Print Slim Fit Polo T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1751', 'Joggers with Insert Pockets', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1750', 'Printed Slim Fit Shirt with Patch Pocket', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1749', 'Slim Fit Checked Pants', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1748', '551Z Mid-Wash 5-Pocket Straight Jeans', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1747', 'Floral Slim Fit Shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1746', 'Colourblock Bermuda Shorts with Insert Pockets', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1745', 'Shirt with Spread Collar', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1744', 'Textured Track Pants with Contrast Taping', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1743', 'Skinny Flat-Front Trousers', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1742', 'Pack of 3 Printed Trunks', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1741', 'Washed Slim Fit Jeans', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1740', '511 Redloop Light-Washed Slim Fit Jeans', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1739', 'Three-Fourth Shorts with Insert Pockets', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1738', 'Slim Fit Shirt with Patch Pocket', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1737', 'Quick-dry Thumb-Hole Polo T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1736', 'Mid-Wash Distressed Skinny Fit Jeans', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1735', 'Flat-Front Slim Fit Chinos', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1734', 'Shirt with Patch Pocket', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1733', 'Printed Slim Fit Shirt with Patch Pocket', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1732', 'Mid-Wash Skinny Fit Jeans', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1731', 'Track Pants with Insert Pocket', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1730', 'Lightly Washed Slim Fit Jeans with Whiskers', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1729', 'Slim Fit Flat-Front Jogger Pants', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1728', 'Mid-Rise Joggers with Insert Pockets', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1727', 'Micro Print Slim Fit Shirt with Patch Pocket', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1726', 'Button-Down Collar Shirt with Patch Pocket', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1725', 'Placement Brand Print Joggers with Insert Pockets', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1724', 'Mid-Wash Slim Fit Jeans', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1723', 'Hooded Fuji Jacket with Double Zipper', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1722', 'Mid-Wash Mid-Rise Skinny Jeans', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1721', 'Run Colourblock Hooded Jacket', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1720', 'Cotton Shirt with Patch Pocket', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1719', 'Striped Full Sleeves T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1718', 'Cotton Hoodie with Kangaroo Pockets', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1717', 'Mid Wash Skinny Jeans', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1716', 'Sunscorched Chino Shorts with Elasticated Drawstring Waist', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1715', 'Tapered Fit Flat-Front Trousers', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1714', 'Striped Crew-Neck T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1713', 'Joggers with Insert Pockets', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1712', 'Panelled Track Pants with Insert Pockets', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1711', 'Logo Print Baseball Cap', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1710', 'Typographic Print Crew-Neck T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1709', 'Logo Print Crew-Neck T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1708', 'Slim Fit Polo T-shirt with Contrast Tipping', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1707', 'Slim Fit Knitted Shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1706', 'Camouflage Print Slim Cargo Shorts', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1705', 'Typographic Print Crew-Neck T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1704', 'Slim Fit Shirt with Patch Pocket', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1703', 'Slim Fit Crew-Neck T-shirt with Brand Logo Print', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1702', 'Printed Flat-Front Trousers with Insert Pockets', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1701', 'Striped Slim Fit Shirt with Patch Pocket', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1700', 'Checked Cotton Flat-Front Chinos', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1699', 'Washed Skinny Stretch Jeans', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1698', 'Superstate Polo T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1697', 'Shorts with Elasticated Waist', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1696', 'Flat-Front Tapered Chinos with Insert Pockets', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1695', 'Lightly Washed Slim Jeans', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1694', 'Mid-Wash Slim Fit Jeans', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1693', 'Checked Slim Fit Shirt with Patch Pocket', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1692', 'Printed Flat-Front City Shorts', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1691', 'Slim Fit Flat-Front Trousers', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1690', 'Striped Slim Fit Shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1689', 'Graphic Print Crew-Neck Cotton T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1688', 'Colourblock Quick-dry Crew-Neck T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1687', 'Solid Slim Fit Crew- Neck T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1686', 'Slim Fit Shirt with Patch Pocket', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1685', 'Ditsy Print Shirt with Patch Pocket', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1684', 'Distressed Mid-Rise Skinny Jeans', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1683', '512 Light-Washed Slim Fit Jeans', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1682', 'Striped Shirt with Patch Pocket', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1681', 'Sleeveless Hoodie with Split Kangaroo Pockets', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1680', 'Shorts with Elasticated Waist', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1679', 'Tropical Print Shirt with Patch Pocket', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1678', 'Checked Slim Fit Shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1677', 'Joggers with Insert Pockets', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1676', 'Cropped Slim Fit Chinos with Slip Pockets', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1675', 'Logo Print Track Pants with Insert Pockets', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1674', 'City Shorts with Insert Pockets', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1673', 'Classic Poolside Polo T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1672', 'Textured V-neck Pullover', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1671', 'Placement Striped Joggers with Drawstring', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1670', 'Henley T-shirt with Full Sleeves', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1669', 'Printed Band-Collar Slim Fit Shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1668', 'Stripe-Knit Hooded T-shirt with Kangaroo Pocket', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1667', 'Heathered Henley T-shirt with Contrast Panel', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1666', 'Printed Pyjamas with Elasticated Waist', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1665', 'Leaf Print Cargo Shorts', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1664', 'Slim Fit Polo T-shirt with Brand Print', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1663', 'LFC MNK DF STRK TOP SS Crew-Neck T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1662', 'Printed Slim Fit Shirt with Patch Pocket', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1661', 'Colourblock Mandarin Collar Shirt ', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1660', 'Solid Mid Rise Jeans', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1659', 'Washed Slim Fit Shorts with Insert Pockets', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1658', 'Typographic Print Hoodie with Kangaroo Pockets', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1657', 'Heathered Polo T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1656', 'Polo T-shirt with Shoulder Taping', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1655', 'Colourblock Crew-Neck T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1654', 'Checked Shirt with Patch Pocket', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1653', 'Trunks with Elasticated Waistband', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1652', 'Slim Fit Shirt with Patch Pocket', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1651', 'Premium Checked Slub Cotton Amsler Shirt with Patch Pocket', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1650', 'Slim Fit Shirt with Colourblock Stripe', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1649', 'Heathered Track Pants with Insert Pockets', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1648', 'NP35 BSC Slim Fit Checked Shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1647', 'Mid-Wash Slim-Fit Jeans', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1646', 'Printed Band-Collar Slim Fit Shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1645', 'Checked Slim Fit Shirt with Patch Pocket', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1644', 'Polo T-shirt with Patch Pocket', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1643', 'Reversible Shirt with Spread Collar', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1642', 'Slim Fit Shirt with Cut-Away Collar', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1641', 'Checked Slim Fit Shirt with Patch Pocket', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1640', 'Lightly Washed Slim Fit Jeans', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1639', 'Cotton Shirt with Patch Pocket', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1638', 'Pack of 3 Socks with Logo Pattern', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1637', 'Polo T-shirt with Contrast Tipping', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1636', 'Solid Regular Fit Polo T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1635', 'Trider Typographic Print Crew-Neck T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1634', 'Dot Print Crew-Neck T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1633', 'Pack of 2 City Shorts with Drawstring Waist', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1632', 'Striped Slim Fit Long Kurta', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1631', 'Colourblock Sleeveless Sweater', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1630', 'Bomber Jacket with Insert Pockets', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1629', 'Slim Fit Crew-Neck T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1628', 'Light-Wash Slim Fit Jeans', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1627', 'Slim Fit Cargo Shorts with Insert Pockets', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1626', 'Solid Slim Jeans', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1625', 'Flat-Front Shorts with Insert Pockets', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1624', 'Pack of 2 Slim Fit Track Pants', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1623', 'Slim Fit Flat-Front Trousers', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1622', 'Colourblock Sweatshirt with Ribbed Hems', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1621', 'Textured Slim Fit Flat-Front Chinos', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1620', 'Shorts with Contrast Side Taping', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1619', 'Lightly Washed Slim Fit Jeans', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1618', 'Polo T-shirt with Patch Pocket', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1617', 'Striped Cotton Polo T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1616', 'Flat-Front Tapered Fit Trousers', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1615', 'Logo Print Crew-Neck T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1614', 'Graphic Print Crew-Neck T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1613', 'Core Skinny Fit Jeans', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1612', 'Micro Print Cuffed Joggers with Insert Pockets', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1611', 'Graphic Print Crew-Neck T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1610', 'Checked Slim Fit Shirt with Patch Pocket', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1609', 'Slim Fit Chinos with Insert Pockets', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1608', 'Lightly-Washed Low-Rise Skinny Jeans', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1607', 'Geometric Print Scoop-Neck T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1606', 'Blr Mb 511 Mid-Rise Slim Jeans', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1605', 'High-Neck Henley Pullover with Ribbed Hems', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1604', 'Slub Knit Heathered V-neck T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1603', 'Tapered Fit Flat-Front Trousers', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1602', 'Typographic Print Crew-Neck T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1601', 'Micro Print Shirt with Patch Pocket', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1600', 'Pack of 5 Crew-Neck T-shirts', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1599', '517 Mid Rise Boot Cut Jeans', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1598', 'Oxford Shirt With Button-Down Collar', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1597', 'Solid Sleeveless Cotton Vest', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1596', 'Heavy Washed Mid-Rise Jeans', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1595', 'Micro Print Shirt with Patch Pocket', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1594', 'Textured Flat-Front Walk Shorts', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1593', 'Solid Regular Fit Shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1592', 'Track Pants with Elasticated Waitband', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1591', 'Straight Track Pants with Insert Pockets', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1590', 'Striped Quick-dry Polo T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1589', 'Striped Crew-Neck T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1588', 'Slim Fit Flat-Front Trousers', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1587', 'Zip-Front Slim Fit Jacket with Insert Pockets', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1586', 'Striped Slim Fit Shirt with Patch Pocket', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1585', 'Graphic Print Regular Fit Shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1584', 'Striped Polo T-shirt with Vented Hemline', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1583', 'Pack of 2 Trunks', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1582', 'Slim Fit Shirt with Typographic Print', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1581', 'Pack of 2 Crew-Neck T-shirts', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1580', 'Run Crew-Neck T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1579', 'Relaxed Fit Flat-Front Trousers', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1578', 'Graphic Print Crew-Neck  T-shirt ', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1577', 'Micro Print Shirt with Patch Pocket', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1576', 'Slim Fit Shirt with Flap Pockets', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1575', 'Shirt with Band Collar', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1574', 'Fastdry Active Training Jacket', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1573', 'Striped Shirt with Patch Pocket', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1572', 'Flat-Front Trousers with Insert Pockets', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1571', 'Graphic Print Crew-Neck T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1570', 'Mid-Rise Slim Fit Jeans', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1569', 'Heavy-Wash Distressed Slim Fit Jeans', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1568', 'Heathered Shirt with Contrast Taping', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1567', 'Shirt with Contrast Taping', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1566', 'Heathered Polo T-shirt with Zip Closure', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1565', 'Checked Slim Fit Polo T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1564', 'Striped Slim Fit Shirt with Patch Pocket', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1563', 'Crew-Neck T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1562', 'Full Sleeves Sweatshirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1561', 'Striped Polo T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1560', 'Distressed Slim Fit Jeans', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1559', 'Typographic Print Crew-Neck T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1558', 'Joggers with Insert Pockets', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1557', 'Checked Shirt with Patch Pocket', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1556', 'Superstate Polo T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1555', 'High-Neck Sweatshirt with Ribbed Hems', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1554', 'Heathered Henley T-shirt with Patch Pocket', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1553', 'Polo T-shirt with Contrast Stripe Details', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1552', 'Checked Slim Fit Shirt with Patch Pocket', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1551', 'Checked Mid-Rise Flat-Front Cropped Slim Fit Chinos', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1550', 'Mid Distressed Skinny Jeans', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1549', 'Textured Slim Fit Flat-Front Chinos', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1548', 'Lightly Washed Skinny Jeans', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1547', 'Washed Straight Jeans', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1546', 'Washed Slim Fit Jeans', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1545', 'Pack of 3 Cotton T-shirts', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1544', 'Striped Shirt with Patch Pocket', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1543', 'Typographic Print Crew-Neck T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1542', 'Striped Cotton Shirt with Patch Pocket', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1541', 'Leaf Print Cotton Shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1540', 'Royce Range Heat Flat-Front Slim Trousers', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1539', 'Flat-Front Chinos with 5-Pocket Styling', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1538', 'Mid-Wash Skinny Fit Jeans', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1537', 'Washed Slim Fit Shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1536', 'Mid-Wash Slim-Fit Jeans', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1535', 'Lightly Washed Low-Rise Skinny Fit Jeans', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1534', 'Slim Fit Crew-Neck T-shirt with Thumbhole', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1533', 'Lightly Washed Slim Fit Jeans', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1532', 'Typographic Print Polo T-shirt with Step Hem', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1531', 'Printed Trunks with Elasticated Waistband', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1530', 'Typographic Print Hooded T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1529', 'Crew-Neck T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1528', 'Hooded T-shirt with Colourblock Sleeves', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1527', 'Slub Knit Crew-Neck T-shirt', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1526', 'Solid Mandarin Neck Kurta', 'mangal')
insert into ajiomen(File_name, Product_name, category)values('ajio-1525', 'Straight Running